apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cartonization.fullname" . }}
  namespace: {{ .Values.namespace | default "paklog" }}
  labels:
    {{- include "cartonization.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit | default 3 }}
  strategy:
    type: {{ .Values.deployment.strategy.type | default "RollingUpdate" }}
    {{- if eq (.Values.deployment.strategy.type | default "RollingUpdate") "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable | default 0 }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "cartonization.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cartonization.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cartonization.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        {{- if .Values.service.managementPort }}
        - name: management
          containerPort: {{ .Values.service.managementPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path | default "/actuator/health/liveness" }}
            port: {{ .Values.livenessProbe.port | default "management" }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 60 }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path | default "/actuator/health/readiness" }}
            port: {{ .Values.readinessProbe.port | default "management" }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.startupProbe.path | default "/actuator/health/liveness" }}
            port: {{ .Values.startupProbe.port | default "management" }}
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds | default 0 }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.startupProbe.failureThreshold | default 30 }}
        {{- end }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.springProfile | default "prod" | quote }}
        - name: JAVA_OPTS
          value: {{ .Values.javaOpts | default "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0" | quote }}
        {{- if .Values.mongodb.enabled }}
        - name: MONGODB_URI
          value: {{ .Values.mongodb.uri | quote }}
        {{- if .Values.mongodb.existingSecret }}
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.existingSecret }}
              key: mongodb-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.existingSecret }}
              key: mongodb-password
        {{- end }}
        {{- end }}
        {{- if .Values.postgresql.enabled }}
        - name: DATABASE_URL
          value: {{ .Values.postgresql.url | quote }}
        {{- if .Values.postgresql.existingSecret }}
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.existingSecret }}
              key: postgresql-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.existingSecret }}
              key: postgresql-password
        {{- end }}
        {{- end }}
        {{- if .Values.kafka.enabled }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.bootstrapServers | quote }}
        {{- end }}
        {{- if .Values.redis.enabled }}
        - name: REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        {{- if .Values.redis.existingSecret }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.existingSecret }}
              key: redis-password
        {{- end }}
        {{- end }}
        {{- if .Values.observability.enabled }}
        - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
          value: {{ .Values.observability.otlp.endpoint | quote }}
        {{- if .Values.observability.loki.enabled }}
        - name: MANAGEMENT_LOKI_URL
          value: {{ .Values.observability.loki.url | quote }}
        {{- end }}
        {{- end }}
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
