spring:
  application:
    name: cartonization-service

  profiles:
    active: local

  data:
    mongodb:
      uri: mongodb://cartonization_user:cartonization_pass@localhost:27017/cartonization
      auto-index-creation: false

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  kafka:
    bootstrap-servers: localhost:9092

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

app:
  kafka:
    topics:
      cartonization-requests: cartonization.requests
      cartonization-responses: cartonization.responses
      cartonization-solutions: cartonization.solutions
      cartonization-events: cartonization.events
      carton-management-requests: carton.management.requests
      cartonization-requests-dlq: cartonization.requests.dlq
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:cartonization-service}
      auto-offset-reset: earliest
      enable-auto-commit: false
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
      max-poll-records: 500
      max-poll-interval-ms: 300000
      concurrency: 3
  cache:
    warmup:
      enabled: true
      common-skus:
        - PROD001
        - PROD002
        - PROD003

integration:
  product-catalog:
    base-url: ${PRODUCT_CATALOG_BASE_URL:http://localhost:8081}

resilience4j:
  circuitbreaker:
    instances:
      product-catalog:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

  retry:
    instances:
      product-catalog:
        max-attempts: 3
        wait-duration: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.paklog.cartonization: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

product-catalog:
  base-url: http://localhost:8081
  timeout: 5000